name: organics_salary
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  line_icons: ^2.0.3
  get: ^4.7.2
  http: ^1.1.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  animated_segmented_tab_control: ^2.0.0
  syncfusion_flutter_datepicker: ^27.1.48
  image_picker: ^1.0.4
  dotted_border: ^2.1.0
  date_format: ^2.0.7
  sidebarx: ^0.17.1
  collection: ^1.18.0
  url_launcher: ^6.2.2
  font_awesome_flutter: ^10.7.0
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  custom_pin_screen: ^1.0.1
  local_auth: ^2.1.7
  carousel_grid: ^1.0.5
  dio: ^5.4.0
  http_parser: ^4.0.2
  syncfusion_flutter_charts: ^27.1.48
  percent_indicator: ^4.2.3
  timezone: ^0.9.2
  camera: ^0.11.0+2
  get_it: ^7.6.7
  carousel_slider: ^5.0.0
  floating_frosted_bottom_bar: ^0.0.1
  syncfusion_flutter_core: ^27.1.48
  upgrader: ^11.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.7.10
  flutter_advanced_drawer: ^1.3.6
  file_picker: ^8.0.3
  nb_utils: ^7.0.2
  bcrypt: ^1.1.3
  syncfusion_flutter_datagrid: ^27.1.48
  # ai_barcode_scanner: ^5.2.2
  icons_launcher: ^3.0.0
  mobile_scanner: ^5.2.3
  ai_barcode_scanner: ^5.2.2
  webview_flutter: ^4.10.0
  firebase_core: ^2.32.0
  drop_down_list: ^0.0.8
  syncfusion_flutter_pdfviewer: ^27.2.5
  tab_container: ^3.5.3
  buttons_tabbar: ^1.3.15
  flutter_floating_bottom_bar: ^1.2.1+1
  permission_handler: ^12.0.0+1
  easy_image_viewer: ^1.5.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  material_symbols_icons: ^4.2815.1
  photo_view: ^0.15.0
  saver_gallery: ^4.0.1
  flutter_html: ^3.0.0
  flutter_svg: ^2.2.1
  loading_indicator: ^3.1.1
  pdfx: ^2.6.0 # แปลงหน้า PDF เป็นภาพ
  # image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/coin/
    - assets/img/menu/
    - assets/img/time_history/
    - assets/img/notification/
    - assets/img/news/
    - assets/img/user_demo/
    - assets/img/car/
    - assets/img/honor/
    - assets/img/social_security/
    - assets/img/transection/
    - assets/img/document_contract/
    - assets/img/equipment/
    - assets/img/group_security/
    - .env

icons_launcher:
  image_path: "assets/img/logo.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
