// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGo1Az_x_6qQD6fZXj62hRN4bQovOmSe4',
    appId: '1:893163642766:web:94d3982f3fa7d64c32cedf',
    messagingSenderId: '893163642766',
    projectId: 'organicshr-1b1c5',
    authDomain: 'organicshr-1b1c5.firebaseapp.com',
    storageBucket: 'organicshr-1b1c5.appspot.com',
    measurementId: 'G-N954V8JEXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfiNpgGaRPBMooH6T7wox5b1y-iNxwIKs',
    appId: '1:893163642766:android:c8c97d0b0ce501c732cedf',
    messagingSenderId: '893163642766',
    projectId: 'organicshr-1b1c5',
    storageBucket: 'organicshr-1b1c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7bYmpsL2SqzY0GW8aHIt1hTRHu3rwmGk',
    appId: '1:893163642766:ios:3d088a8bfc67a18a32cedf',
    messagingSenderId: '893163642766',
    projectId: 'organicshr-1b1c5',
    storageBucket: 'organicshr-1b1c5.firebasestorage.app',
    iosBundleId: 'com.organicscosme.hr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7bYmpsL2SqzY0GW8aHIt1hTRHu3rwmGk',
    appId: '1:893163642766:ios:2bf52cabfe01e13332cedf',
    messagingSenderId: '893163642766',
    projectId: 'organicshr-1b1c5',
    storageBucket: 'organicshr-1b1c5.appspot.com',
    iosBundleId: 'com.organicscosme.hr',
  );
}
